-- MySQL Script generated by MySQL Workbench
-- Wed Jun 28 23:01:36 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema projektmarktplatzdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projektmarktplatzdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projektmarktplatzdb` DEFAULT CHARACTER SET utf8 ;
USE `projektmarktplatzdb` ;

-- -----------------------------------------------------
-- Table `projektmarktplatzdb`.`projektmarktplatz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projektmarktplatzdb`.`projektmarktplatz` (
  `ID` INT NOT NULL,
  `Bezeichnung` VARCHAR(255) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projektmarktplatzdb`.`partnerprofil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projektmarktplatzdb`.`partnerprofil` (
  `ID` INT NOT NULL,
  `Erstelldatum` DATE NULL,
  `Aenderungsdatum` DATE NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projektmarktplatzdb`.`organisationseinheit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projektmarktplatzdb`.`organisationseinheit` (
  `ID` INT NOT NULL,
  `Typ` CHAR(1) NULL,
  `Name` VARCHAR(255) NULL,
  `Vorname` VARCHAR(255) NULL,
  `Email` VARCHAR(255) NULL,
  `Strasse` VARCHAR(255) NULL,
  `PLZ` INT NULL,
  `Ort` VARCHAR(255) NULL,
  `Tel` VARCHAR(255) NULL,
  `Partnerprofil_ID` INT NULL,
  `UAdmin_ID` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Organisationseinheit_Partnerprofil1_idx` (`Partnerprofil_ID` ASC),
  INDEX `fk_UAdmin_fk_idx` (`UAdmin_ID` ASC),
  CONSTRAINT `fk_Organisationseinheit_Partnerprofil1`
    FOREIGN KEY (`Partnerprofil_ID`)
    REFERENCES `projektmarktplatzdb`.`partnerprofil` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UAdmin_fk`
    FOREIGN KEY (`UAdmin_ID`)
    REFERENCES `projektmarktplatzdb`.`organisationseinheit` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projektmarktplatzdb`.`projekt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projektmarktplatzdb`.`projekt` (
  `ID` INT NOT NULL,
  `Name` VARCHAR(255) NULL,
  `Startdatum` DATE NULL,
  `Enddatum` DATE NULL,
  `Beschreibung` TEXT NULL,
  `Projektmarktplatz_ID` INT NOT NULL,
  `Projektleiter_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Projekt_Projektmarktplatz_idx` (`Projektmarktplatz_ID` ASC),
  INDEX `fk_Projekt_Organisationseinheit2_idx` (`Projektleiter_ID` ASC),
  CONSTRAINT `fk_Projekt_Projektmarktplatz`
    FOREIGN KEY (`Projektmarktplatz_ID`)
    REFERENCES `projektmarktplatzdb`.`projektmarktplatz` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Projekt_Organisationseinheit2`
    FOREIGN KEY (`Projektleiter_ID`)
    REFERENCES `projektmarktplatzdb`.`organisationseinheit` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projektmarktplatzdb`.`beteiligung`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projektmarktplatzdb`.`beteiligung` (
  `ID` INT NOT NULL,
  `Personentage` INT NULL,
  `Startdatum` DATE NULL,
  `Enddatum` DATE NULL,
  `Projekt_ID` INT NOT NULL,
  `Organisationseinheit_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Beteiligung_Projekt1_idx` (`Projekt_ID` ASC),
  INDEX `fk_Beteiligung_Organisationseinheit1_idx` (`Organisationseinheit_ID` ASC),
  CONSTRAINT `fk_Beteiligung_Projekt1`
    FOREIGN KEY (`Projekt_ID`)
    REFERENCES `projektmarktplatzdb`.`projekt` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Beteiligung_Organisationseinheit1`
    FOREIGN KEY (`Organisationseinheit_ID`)
    REFERENCES `projektmarktplatzdb`.`organisationseinheit` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projektmarktplatzdb`.`ausschreibung`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projektmarktplatzdb`.`ausschreibung` (
  `ID` INT NOT NULL,
  `Bezeichnung` VARCHAR(255) NULL,
  `Ausschreibungstext` TEXT NULL,
  `Bewerbungsfrist` DATE NULL,
  `Projekt_ID` INT NOT NULL,
  `Partnerprofil_ID` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Ausschreibung_Projekt1_idx` (`Projekt_ID` ASC),
  INDEX `fk_Ausschreibung_Partnerprofil1_idx` (`Partnerprofil_ID` ASC),
  CONSTRAINT `fk_Ausschreibung_Projekt1`
    FOREIGN KEY (`Projekt_ID`)
    REFERENCES `projektmarktplatzdb`.`projekt` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ausschreibung_Partnerprofil1`
    FOREIGN KEY (`Partnerprofil_ID`)
    REFERENCES `projektmarktplatzdb`.`partnerprofil` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projektmarktplatzdb`.`bewerbung`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projektmarktplatzdb`.`bewerbung` (
  `ID` INT NOT NULL,
  `Erstelldatum` DATE NULL,
  `Bewerbungstext` TEXT NULL,
  `Ausschreibung_ID` INT NOT NULL,
  `Organisationseinheit_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Bewerbung_Ausschreibung1_idx` (`Ausschreibung_ID` ASC),
  INDEX `fk_Bewerbung_Organisationseinheit1_idx` (`Organisationseinheit_ID` ASC),
  CONSTRAINT `fk_Bewerbung_Ausschreibung1`
    FOREIGN KEY (`Ausschreibung_ID`)
    REFERENCES `projektmarktplatzdb`.`ausschreibung` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bewerbung_Organisationseinheit1`
    FOREIGN KEY (`Organisationseinheit_ID`)
    REFERENCES `projektmarktplatzdb`.`organisationseinheit` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projektmarktplatzdb`.`bewertung`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projektmarktplatzdb`.`bewertung` (
  `ID` INT NOT NULL,
  `Wert` FLOAT NULL,
  `Stellungnahme` TEXT NULL,
  `Erstelldatum` DATE NULL,
  `Bewerbung_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Bewertung_Bewerbung1_idx` (`Bewerbung_ID` ASC),
  CONSTRAINT `fk_Bewertung_Bewerbung1`
    FOREIGN KEY (`Bewerbung_ID`)
    REFERENCES `projektmarktplatzdb`.`bewerbung` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projektmarktplatzdb`.`eigenschaft`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projektmarktplatzdb`.`eigenschaft` (
  `ID` INT NOT NULL,
  `Name` VARCHAR(255) NULL,
  `Wert` VARCHAR(255) NULL,
  `Partnerprofil_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Eigenschaft_Partnerprofil1_idx` (`Partnerprofil_ID` ASC),
  CONSTRAINT `fk_Eigenschaft_Partnerprofil1`
    FOREIGN KEY (`Partnerprofil_ID`)
    REFERENCES `projektmarktplatzdb`.`partnerprofil` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projektmarktplatzdb`.`unternehmen_has_person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projektmarktplatzdb`.`unternehmen_has_person` (
  `Unternehmen_ID` INT NOT NULL,
  `Person_ID` INT NOT NULL,
  PRIMARY KEY (`Unternehmen_ID`, `Person_ID`),
  INDEX `fk_Person_idx` (`Person_ID` ASC),
  INDEX `fk_Unternehmen_idx` (`Unternehmen_ID` ASC),
  CONSTRAINT `fk_Person`
    FOREIGN KEY (`Person_ID`)
    REFERENCES `projektmarktplatzdb`.`organisationseinheit` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Unternehmen`
    FOREIGN KEY (`Unternehmen_ID`)
    REFERENCES `projektmarktplatzdb`.`organisationseinheit` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
